directories:
  output: ../../release
  buildResources: build
files:
  - filter:
      - dist
extraMetadata:
  version: 1.0.0
appId: com.azur-lane-auto-script.webapp
productName: AzurLaneAutoScript
afterSign: electron-builder-notarize
win:
  artifactName: ${name}_setup_${version}.${ext}
  target:
    - nsis
nsis:
  oneClick: false
  perMachine: true
  allowToChangeInstallationDirectory: true
  license: build/license.txt
mac:
  category: public.app-category.developer-tools
  target:
    - dmg
  artifactName: ${name}_setup_${version}.${ext}
  hardenedRuntime: true
  gatekeeperAssess: false
  darkModeSupport: true
  entitlements: build/entitlements.mac.plist
  entitlementsInherit: build/entitlements.mac.plist
dmg:
  icon: build/volume.icns
  background: build/background.png
  title: ${productName}
  iconSize: 80
  window:
    height: 422
    width: 600
  contents:
    - type: file
      x: 144
      'y': 199
    - type: link
      path: /Applications
      x: 451
      'y': 199
mas:
  hardenedRuntime: false
  darkModeSupport: true
  provisioningProfile: build/embedded.provisionprofile
  category: public.app-category.productivity
  entitlements: build/entitlements.mas.plist
  entitlementsInherit: build/entitlements.mas.inherit.plist
  asarUnpack: []
linux:
  artifactName: ${name}_setup_${version}.${ext}
  icon: build/icon.png
  synopsis: azur lane auto script
  category: Development
publish:
  - github
compression: maximum
npmRebuild: false
electronVersion: 26.6.4
